### ISSUE TITLE
SSL certificate

### ISSUE THREAD

**Issue by rogerjbos** [bbrookfield/alexa-thermostat#1]
I am trying hard to get the sample skill working, but I am having trouble figuring out how to configure my Pi 2 to present the SSL certificate so the https endpoint will work.  Currently Amazon gives the following error:
There was an exception during the SSL hand shake. Please check the certificate you have provided.
I have create a key and certificate from CAcert.org following their tutorial, but I am not even sure if my Pi 2 is using Apache.  If it is, I can't figure out where the proper config file is because it is not in /etc/apache2/sites-available.

The README didn't really discuss the SSL part.  Could anyone provide me with some more details?  Thanks in advance.

**Comment by dvideby0** [comment]
My apologies for the delay. Unfortunately, I am not sure what the pi uses out of the box (I assumed you installed whatever OS you wanted). When we started writing this we used Heroku to deploy to which will give you SSL by default. They have a free dyno type and its really easy to work out if you are interested in going that route. Unfortunately I dont have enough time at the moment to look into your specific pi issue.
