### ISSUE TITLE
Port Problem

### ISSUE THREAD

**Issue by droidforever** [bbrookfield/alexa-thermostat#12]
When I try to run PORT=9000 node app.js I get this error:
'PORT' is not recognized as an internal or external command,
operable program or batch file.
I can enable a port inside the app.js but I have read other's comments that I shouldn't do that.
Can you please tell me how to get around this issue?
I tried Heroku and finally got it running but it seems to be hit and miss and looking at my log from there I see timeout issues so I would rather run this locally.

**Comment by bbrookfield** [comment]
refer to this info on using express();
https://expressjs.com/en/api.html
