### ISSUE TITLE
Async/Promise in Modules?

### ISSUE THREAD

**Issue by ghost** [bbrookfield/alexa-thermostat#3]
Is there a way I can utilize Async or Promises in the modules? I'm deconstructing this into my own project, and I'd like to make an http request inside of the sample module. When I do so, it works however, I can't seem to send it back out to `init()` in `app.js` so that it returns JSON correctly:

``` js
/* project/app_modules/alexa-sampleskill/index.js */

// process the single slot supported by this skill
sampleApp.intent('people', function(req, res) {
    // Sample Jazz Linked API Request
    request('http://linkedjazz.org/api/people/search/' + req.slot('musician'), function(err, response, body) {
        if (!err && response.statusCode == 200) {
            // Request is OK
            // body is an array
            var content = JSON.parse(body);
            if (content[0].name) {
                console.log(content[0].name);   
            } else {
                console.error("no one found by that name.");
            }
        } else {
            // Request is NOT OK
            console.error(err);
        }
    });

    // Naturally, these are never hit, at least not in the int() function inside of app.js where I get a JSON response back
    res.card("Jazz Info Skill","You said " + req.slot('musician') + ", your skill is working");
    res.say("You said " + req.slot('musician') + ", your skill is working");
});
```

**Comment by dvideby0** [comment]
Have you tried using bluebird and their promisify function? It follows the standard callback pattern of `err, res`

**Comment by dvideby0** [comment]
Here is a link.. http://bluebirdjs.com/docs/api/promise.promisifyall.html

**Comment by ghost** [comment]
Thanks. I ended up using https.get()'s callback[ like is documented](https://www.npmjs.com/package/alexa-app#asynchronous-intent-handler) in alexa-app module, but a promise should have worked (I tried it initially).
