### ISSUE TITLE
Can't seem to see what's wrong

### ISSUE THREAD

**Issue by devaudio** [bbrookfield/alexa-thermostat#5]
I installed it , have AWS SDK all setup (i have 2 other skills loaded) - but trying to get this one to work i've tried:

`THERMOSTAT_URL=upstairs-thermostat PORT=9000 node app.js`
`THERMOSTAT_URL="http://upstairs-thermostat" PORT=9000 node app.js`

it's valid --> 

`curl http://upstairs-thermostat/tstat`
`{"temp":71.00,"tmode":1,"fmode":0,"override":0,"hold":0,"t_heat":68.00,"tstate":0,"fstate":0,"time":{"day":1,"hour":15,"minute":47},"t_type_post":0}`

but All i seem to get from this app, when i call 'thermostat'  is:

`Cannot GET /thermostat`

and no errors or anything at all in log/stdout

I am accessing it via:

> ProxyPass /thermostat  http://192.168.0.17:9000/thermostat
> ProxyPassReverse /thermostat  http://192.168.0.17:9000/thermostat

A setup that allows my other apps to access it via an internet facing website, and still talk to local stuff. 

How can I further debug what is going on?

**Comment by bbrookfield** [comment]
your THERMOSTAT_URL="http://upstairs-thermostat" PORT=9000 node app.js is wrong. The URL must be a standard HTTP request that can be reached from outside your home network.

You would normally create a domain using one of the fee or cheap Dynamic DNS services that points to your home network external IP address.

Example:  MyName.ddns.net  Where MyName is a name you define when creating the Dynamic DNS.and ddns.net is the Dynamic DNS provider host.

Once that is done and you can reach something on your home network from outside (I use my cell phone set to Mobile Network (3g/LTE) to test)

The THERMOSTAT_URL would look like
THERMOSTAT_URL="http://MyName.ddns.net:9000"

Hope this helps.

Bill B

**Comment by devaudio** [comment]
so i have a domain and such, it's what i am using the proxypass for....  if i set THERMOSTAT_URL to that , how does it know to connect to   whatever-host/tstat    to get to the thermostats? or do you have both myname.ddns.net/tstat & myname.ddns.net:9000 both on same host and tstat is reachable from outside world as well?

**Comment by bbrookfield** [comment]
No sure what Proxypass is so I can only give examples of what I know to work.

you would add :9000 to the dynamic domain name in your ASK skill. Where 9000 is a port forward you have define in your router to the internal network address of your thermostat.

example  MyName.ddns.net is your dynamic name
in your ASK skill set the THERMOSTAT_URL to "http://MyName.ddns.net:9000"

No sure what proxypass is so I can only give examples of what I know to work.

**Comment by devaudio** [comment]
Proxy Pass works like this:

[Amazon Cloud]   --->  [DMZ host running https]   --> passes request to internal IP

So like, my Kodi/XMBC alexa stuff goes   [amazon cloud] ---> homenet.devaudio.org/xbmc --> [xbmc 192.168.0.22] --> back to alexa

homenet.devaudio.org sits on internet, but xbmc runs on an internal box I have that has no internet connection, and i can't install node/anything on it, but it has an API. So i can transparently proxy it that way, and at the same time, control access at the DMZ host.   Just a different method, slightly more complex than your setup

**Comment by devaudio** [comment]
the proxy pass portion is just for that URI --> /xbmc   the other stuff is served from other things

**Comment by bbrookfield** [comment]
OK, thank you for the explanation. Are you running a Self Signed certificate to support https requests? If so, that may be your problem. Ask Skills have very strict requirements on https from AWS. That is why I use Heroku. 

Bill B

**Comment by devaudio** [comment]
Naw, i got my own cert and all that. I am new to node, and I ended up just giving up and doing what i know -- writing the app in python as a gunicorn/proxypass app :-D
